title: Brandon Chan
description: Ever since I've been in computer science, I have been inspired by so many intelligent people who create amazing projects and share them to the world. The main purpose of this website is to give back and share my projects to the world in the hopes that I can inspire someone out there. Keep in mind, I am no expert and I only wish to give you the tools and motivation that will hopefully benefit your life in some way.
#baseurl: "/BrandonChanWebsite/"
#url: "https://brandevcode.github.io/"
#baseurl: ""
#url: "brandonchan.ca"
repository: BrandevCode/BrandonChanWebsite
paginate: 5

banner: "/assets/res/banner.jpg" # site banner (load when someone share your page url)
favicon: "/assets/res/favicon.png" # site's favicon (icon left side of your page)
title_font: "/assets/fonts/ufonts.com_opineheavy-regular.ttf" # site's left side logo

# MatJek specific configurations
user: 
  name: "Brandon Chan"
  #email: "brandonchan@hotmail.com"
  #website: "brandonchan.ca"
  avatar: "/assets/res/user2.jpg"
  github: "brandevcode"
google_tracking_id: "UA-172634139-1"
google_site_verification: ""
disqus_shortname: brandonchan.ca

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title


plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

  future: true
